export const SET_SIGNUP = 'SET_SIGNUP'
export const TYPING_USER = 'TYPING_USER'
export const TYPING_EMAIL = 'TYPING_EMAIL'
export const SELECTING_PANEL = 'SELECTING_PANEL'
export const TYPING_PASSWORD = 'TYPING_PASSWORD'
export const ERASING_DATA = 'ERASING_DATA'

