export const SET_SIGNUP = 'SET_SIGNUP'
export const TYPING_USER = 'TYPING_USER'
export const TYPING_EMAIL = 'TYPING_EMAIL'
export const SELECTING_PANEL = 'SELECTING_PANEL'
export const SELECTING_CELL = 'SELECTING_CELL'
export const TYPING_PASSWORD = 'TYPING_PASSWORD'
export const ERASING_DATA = 'ERASING_DATA'
export const SET_LOGIN = 'SET_LOGIN'
export const TYPING_LOGIN = 'TYPING_LOGIN'
export const TYPING_MENU = 'TYPING_MENU'
export const SET_MENU = 'SET_MENU'
export const ERASING_MENU_DATA = 'ERASING_MENU_DATA'
export const TYPING_CATEGORY = 'TYPING_CATEGORY'
export const SET_CATEGORY = 'SET_CATEGORY'
export const TYPING_ABOUT_US = 'TYPING_ABOUT_US'

export const ERASING_USER_DATA = 'ERASING_USER_DATA'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SET_NAVIGATION_FILTER = 'SET_NAVIGATION_FILTER'
export const LOAD_PERSON_DATA = 'LOAD_PERSON_DATA'
export const LOAD_BUSINESS_DATA = 'LOAD_BUSINESS_DATA'
export const GET_DATA_SERVER = 'GET_DATA_SERVER'



export const VisibilityFilters = {
    SHOW_HOME: 'SHOW_HOME',
    SHOW_BUSSINESS_PAGE: 'SHOW_BUSSINESS_PAGE'
    
  }

  export const NavigationFilters = {
    SHOW_HOME_CONTENT: 'SHOW_HOME_CONTENT',
    SHOW_CARTA: 'SHOW_CARTA',
    SHOW_ABOUT_US: 'SHOW_ABOUT_US',
    SHOW_CONTACT_US: 'SHOW_CONTACT_US',
    SHOW_PROFILE: 'SHOW_PROFILE'
    
  }


